namespace: prod

resources:
  - ../../base
  - namespace.yml

patchesStrategicMerge:
  - armeria-sandbox-backend1/deployment.yml
  - armeria-sandbox-backend2/deployment.yml
  - armeria-sandbox-backend3/deployment.yml
  - armeria-sandbox-backend4/deployment.yml
  - armeria-sandbox-frontend/deployment.yml
  - armeria-sandbox-job-kubernetes/deployment.yml

configMapGenerator:
  - name: armeria-sandbox-backend1-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
  - name: armeria-sandbox-backend2-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
  - name: armeria-sandbox-backend3-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
  - name: armeria-sandbox-backend4-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
  - name: armeria-sandbox-frontend-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
  - name: armeria-sandbox-job-kubernetes-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes
      - JAVA_OPTIONS_HEAP_SIZE=256m
      - LOGGING_LEVEL_INFO_MATSUMANA_ARMERIA=INFO
      - KUBERNETES_NAMESPACE=prod

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-backend1
    path: armeria-sandbox-backend1/deployment_patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-backend2
    path: armeria-sandbox-backend2/deployment_patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-backend3
    path: armeria-sandbox-backend3/deployment_patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-backend4
    path: armeria-sandbox-backend4/deployment_patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-frontend
    path: armeria-sandbox-frontend/deployment_patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: armeria-sandbox-job-kubernetes
    path: armeria-sandbox-job-kubernetes/deployment_patch.yml
