# see also:
# https://reboooot.net/post/how-to-specify-mem-limit-on-docker/
version: "2"

services:
  zipkin:
    image: openzipkin/zipkin:2.11.3
    mem_limit: 1073741824  # 1G
    ports:
    - 9411:9411

  prometheus:
    image: prom/prometheus:v2.4.0
    cpu_quota: 30000      # 30%
    mem_limit: 134217728  # 128M
    ports:
    - 9090:9090
    volumes:
    - ./docker-volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  backend1a:
    depends_on:
    - zipkin
    build:
      context: .
      dockerfile: Dockerfile-backend1
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 8081:8081
    - 18686:8686
    - 15005:5005

  backend1b:
    depends_on:
    - zipkin
    build:
      context: .
      dockerfile: Dockerfile-backend1
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 18081:8081
    - 18687:8686
    - 15006:5005

  backend2a:
    depends_on:
    - zipkin
    build:
      context: .
      dockerfile: Dockerfile-backend2
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 8082:8082
    - 28686:8686
    - 25005:5005

  backend3a:
    depends_on:
    - zipkin
    - backend4a
    - backend4b
    build:
      context: .
      dockerfile: Dockerfile-backend3
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 8083:8083
    - 38686:8686
    - 35005:5005

  backend4a:
    depends_on:
    - zipkin
    build:
      context: .
      dockerfile: Dockerfile-backend4
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 8084:8084
    - 48686:8686
    - 45005:5005

  backend4b:
    depends_on:
    - zipkin
    build:
      context: .
      dockerfile: Dockerfile-backend4
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 18084:8084
    - 48687:8686
    - 45006:5005

  frontend:
    depends_on:
    - zipkin
    - backend1a
    - backend1b
    - backend2a
    - backend3a
    - backend4a
    - backend4b
    build:
      context: .
      dockerfile: Dockerfile-frontend
    cpu_quota: 30000      # 30%
    mem_limit: 536870912  # 512M
    ports:
    - 8080:8080
    - 8686:8686
    - 5005:5005
