---
kind: Service
apiVersion: v1
metadata:
  name: armeria-sandbox-backend2
spec:
  type: NodePort
  selector:
    deployment: armeria-sandbox-backend2
  ports:
  - name: app
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 31200
