---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: armeria-sandbox-backend4
spec:
  template:
    metadata:
      labels:
        app: armeria-sandbox-backend4
    spec:
      containers:
      - name: armeria-sandbox-backend4
        ports:
        - containerPort: 5005  # Java debugger
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
