global:
  scrape_interval:     3s
  evaluation_interval: 3s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'zipkin'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['zipkin:9411']

- job_name: 'backend1a'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend1a:8081']

- job_name: 'backend1b'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend1b:8081']

- job_name: 'backend2a'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend2a:8082']

- job_name: 'backend3a'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend3a:8083']

- job_name: 'backend4a'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend4a:8084']

- job_name: 'backend4b'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['backend4b:8084']

- job_name: 'frontend'
  metrics_path: /internal/metrics
  static_configs:
  - targets: ['frontend:8080']
