zipkin:
  endpoint: http://zipkin.default.svc.cluster.local:9411/api/v2/spans

api-servers:
  backend1:
  - host: backend1a
    port: 8081
  - host: backend1b
    port: 8081
  backend2:
  - host: backend2a
    port: 8082
  backend3:
  - host: backend3a
    port: 8083
  backend4:
  - host: backend4a
    port: 8084
  - host: backend4b
    port: 8084

logging:
  level:
    info.matsumana.armeria: DEBUG
